;;; james-org-ocr-test.el --- Slide OCR tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'ox-ascii)

(defmacro james-test/with-ocr (&rest body)
  "Run BODY in a temporary note with an isolated OCR queue and fake engine."
  (declare (indent 0) (debug t))
  `(james-test/with-temporary-directory root
     (let* ((james/org-ocr--queue nil)
            (james/org-ocr--process nil)
            (james/org-ocr--downloads (make-hash-table :test #'equal))
            (james/org-ocr-enabled t)
            (james/org-ocr-program (expand-file-name "ocr-engine" root))
            (image-file (expand-file-name "slide.png" root))
            (note-file (expand-file-name "note.org" root))
            (org-download-display-inline-images nil))
       (james-test/write-file james/org-ocr-program
                              "#!/bin/sh\nread -r trigger\nprintf '%s\\n' 'Quarterly revenue 18 percent'\n")
       (set-file-modes james/org-ocr-program #o700)
       (james-test/write-file image-file "image bytes")
       (james-test/write-file note-file
                              "* Slides\n[[file:slide.png]]\n\nNotes\n")
       (unwind-protect
           (with-current-buffer (find-file-noselect note-file)
             (auto-save-visited-mode -1)
             (goto-char (point-min))
             (search-forward "[[")
             (backward-char 2)
             ,@body)
         (setq james/org-ocr--queue nil)
         (when (process-live-p james/org-ocr--process)
           (delete-process james/org-ocr--process))))))

(defun james-test/ocr-complete ()
  "Release the controlled OCR process and wait briefly for completion."
  (should (process-live-p james/org-ocr--process))
  (process-send-string james/org-ocr--process "complete\n")
  (let ((deadline (+ (float-time) 5)))
    (while (and james/org-ocr--process (< (float-time) deadline))
      (accept-process-output nil 0.02)))
  (should-not james/org-ocr--process))

(defun james-test/ocr-job ()
  "Queue the image at point and return its job without starting a process."
  (should (james/org-ocr--enqueue (org-element-context)))
  (let ((job (pop james/org-ocr--queue)))
    (setf (james/org-ocr-job-hash job)
          (james/org-ocr--hash (james/org-ocr-job-file job)))
    job))

(ert-deftest james/org-ocr-clean-text-normalizes-whitespace-without-joining-lines ()
  (let ((clean (james/org-ocr--clean-text
                " \r\n  Quarterly\t  review \r\n\r\n• Revenue\u00a018  percent\fNext\u202f milestone\u2028* Literal heading\u2029:END:\r ")))
    (should (equal clean
                   "Quarterly review\n• Revenue 18 percent\nNext milestone\n* Literal heading\n:END:"))
    (should (equal clean (james/org-ocr--clean-text clean)))
    (should (equal "" (james/org-ocr--clean-text "\n\t \f\r")))))

(ert-deftest james/org-ocr-new-results-are-cleaned-and-escaped ()
  (james-test/with-ocr
    (should (james/org-ocr--apply (james-test/ocr-job)
                                "  Slide   title\n\n\t* A  bullet\f:END:\n\n"))
    (should (string-match-p
             (regexp-quote ": Slide title\n: * A bullet\n: :END:\n:END:")
             (buffer-string)))
    (should (= 1 (length (org-element-map (org-element-parse-buffer) 'drawer #'identity))))))

(ert-deftest james/org-ocr-cleanup-preserves-metadata-other-text-and-undo ()
  (james-test/with-ocr
    (erase-buffer)
    (let* ((metadata ": sha256: abcdef\n: options: (\"-l\" \"eng\")\n")
           (messy ":   Quarterly   review  \n: \n:  Revenue\t18 percent\n")
           (tidy ": Quarterly review\n: Revenue 18 percent\n")
           (other "\n:KEEP:\nKeep    these spaces\n:END:\n:OCR:\nUser's custom drawer\n:END:\n")
           (before (concat "* Slides\n:OCR:\n" metadata messy ":END:\n"
                           ":OCR:\n" metadata messy ":END:\n" other))
           (expected (string-replace messy tidy before)))
      (insert before)
      (goto-char (point-max))
      (let ((position (copy-marker (point))))
        (james/org-ocr-cleanup-buffer)
        (should (= (point) position)))
      (should (equal expected (buffer-string)))
      (save-excursion
        (goto-char (point-min))
        (search-forward "Quarterly review")
        (should (invisible-p (1- (point)))))
      (set-buffer-modified-p nil)
      (james/org-ocr-cleanup-buffer)
      (should-not (buffer-modified-p))
      (undo-only 1)
      (should (equal before (buffer-string))))))

(ert-deftest james/org-ocr-live-buffer-preserves-edits-point-and-saved-file ()
  (james-test/with-ocr
    (james/org-ocr-image-at-point)
    (goto-char (point-min))
    (insert "Preamble typed while OCR runs\n")
    (goto-char (point-max))
    (insert "User edits before save\n")
    (save-buffer)
    (insert "Unsaved user edits\n")
    (let ((position (copy-marker (point)))
          (disk (with-temp-buffer (insert-file-contents note-file) (buffer-string))))
      (james-test/ocr-complete)
      (should (= (point) position))
      (should (buffer-modified-p))
      (should (string-match-p "Unsaved user edits" (buffer-string)))
      (should (string-match-p "Quarterly revenue" (buffer-string)))
      (should (equal disk (with-temp-buffer
                            (insert-file-contents note-file) (buffer-string)))))))

(ert-deftest james/org-ocr-skips-intervening-link-drawer-image-and-buffer-changes ()
  (dolist (change '(delete-link replace-link edit-drawer delete-drawer
                   replace-image close-buffer read-only))
    (james-test/with-ocr
      (let ((job (james-test/ocr-job)))
        (should (james/org-ocr--apply job "Original transcription")))
      (goto-char (point-min))
      (search-forward "[[")
      (backward-char 2)
      (let ((job (james-test/ocr-job)))
        (pcase change
          ('delete-link (delete-region (point) (line-end-position)))
          ('replace-link (search-forward "slide.png") (replace-match "other.png"))
          ('edit-drawer (search-forward "Original") (replace-match "User corrected"))
          ('delete-drawer
           (let ((drawer (james/org-ocr--drawer (line-end-position))))
             (delete-region (car drawer) (cdr drawer))))
          ('replace-image (james-test/write-file image-file "replacement bytes"))
          ('close-buffer (kill-buffer (current-buffer)))
          ('read-only (setq buffer-read-only t)))
        (should-not (james/org-ocr--apply job "Must not appear"))))))

(ert-deftest james/org-ocr-folds-searchable-text-and-excludes-only-ocr-from-export ()
  (james-test/with-ocr
    (should (james/org-ocr--apply (james-test/ocr-job)
                                "Quarterly revenue\n* False heading\n:END:\n:OTHER:"))
    (goto-char (point-min))
    (search-forward "Quarterly revenue")
    (should (invisible-p (1- (point))))
    (org-fold-show-context 'isearch)
    (should-not (invisible-p (1- (point))))
    (james/org-ocr-fold-drawers)
    (should (invisible-p (1- (point))))
    (james/org-ocr-reveal-search-result)
    (should-not (invisible-p (1- (point))))
    (let ((tree (org-element-parse-buffer)))
      (should (= 1 (length (org-element-map tree 'headline #'identity))))
      (should (= 1 (length (org-element-map tree 'drawer #'identity)))))
    (goto-char (point-max))
    (insert ":KEEP:\nVisible export note\n:END:\n")
    (let ((export (org-export-as 'ascii nil nil t '(:with-drawers t))))
      (should (string-match-p "Visible export note" export))
      (should-not (string-match-p (regexp-opt '("Quarterly revenue" "sha256" "False heading")) export)))
    (should (string-match-p "Quarterly revenue" (buffer-string)))
    (save-buffer)
    (revert-buffer t t)
    (goto-char (point-min))
    (search-forward "Quarterly revenue")
    (should (invisible-p (1- (point))))
    (when (executable-find "rg")
      (with-temp-buffer
        (should (zerop (call-process "rg" nil t nil "Quarterly revenue" note-file)))
        (should (string-match-p "Quarterly revenue" (buffer-string)))))))

(ert-deftest james/org-ocr-reruns-replace-drawer-and-skip-current-hash ()
  (james-test/with-ocr
    (james/org-ocr-image-at-point)
    (james-test/ocr-complete)
    (james/org-ocr-image-at-point)
    (should-not james/org-ocr--process)
    (james/org-ocr-image-at-point t)
    (james-test/ocr-complete)
    (should (= 1 (length (org-element-map (org-element-parse-buffer) 'drawer #'identity))))
    (james/org-ocr-image-at-point)
    (should-not james/org-ocr--process)
    (let ((james/org-ocr-arguments '("-l" "eng" "--psm" "3")))
      (james/org-ocr-image-at-point)
      (james-test/ocr-complete))))

(ert-deftest james/org-ocr-insertion-advice-queues-local-images-once ()
  (james-test/with-ocr
    (erase-buffer)
    (org-download-insert-link image-file image-file)
    (should james/org-ocr--process)
    (james/org-ocr-buffer)
    (should-not james/org-ocr--queue)
    (james-test/ocr-complete)
    (should (string-match-p "Quarterly revenue" (buffer-string)))))

(ert-deftest james/org-ocr-waits-for-native-download-completion ()
  (james-test/with-ocr
    (let ((target (expand-file-name "download.png" root)) completion)
      (cl-letf (((symbol-function 'url-retrieve)
                 (lambda (_url callback &optional arguments &rest _)
                   (setq completion
                         (lambda ()
                           (with-temp-buffer
                             (insert "HTTP/1.1 200 OK\n\nDownloaded image")
                             (apply callback nil arguments)))))))
        (org-download--image/url-retrieve "https://example.invalid/slide.png" target))
      (goto-char (point-max))
      (org-download-insert-link "https://example.invalid/slide.png" target)
      (should-not james/org-ocr--process)
      (should (= 1 (length james/org-ocr--queue)))
      (funcall completion)
      (james-test/ocr-complete)
      (should-not james/org-ocr--queue))))

(ert-deftest james/org-ocr-tracks-external-download-success-and-failure ()
  (dolist (exit-code '(0 1))
    (james-test/with-ocr
      (let (completion)
        (cl-letf (((symbol-function 'async-start)
                   (lambda (_start finish) (setq completion finish))))
          (org-download--image/command "curl %s -o %s" "https://example.invalid/x" image-file))
        (goto-char (point-max))
        (org-download-insert-link "https://example.invalid/x" image-file)
        (should-not james/org-ocr--process)
        (funcall completion exit-code)
        (if (zerop exit-code)
            (james-test/ocr-complete)
          (should-not james/org-ocr--process))
        (should-not james/org-ocr--queue)))))

(ert-deftest james/org-ocr-failure-preserves-image-and-continues-queue ()
  (james-test/with-ocr
    (james-test/write-file james/org-ocr-program
                           "#!/bin/sh\nprintf '%s\\n' 'Not an image' >&2\nexit 1\n")
    (james/org-ocr-image-at-point)
    (let ((deadline (+ (float-time) 5)))
      (while (and james/org-ocr--process (< (float-time) deadline))
        (accept-process-output nil 0.02)))
    (should-not james/org-ocr--process)
    (should (string-match-p "file:slide.png" (buffer-string)))
    (should-not (string-match-p ":OCR:" (buffer-string)))
    (should-not (buffer-modified-p))))

(ert-deftest james/org-ocr-directory-reuses-buffer-with-unsaved-edits ()
  (james-test/with-ocr
    (goto-char (point-max))
    (insert "Unsaved backfill note\n")
    (cl-letf (((symbol-function 'james/org-ocr--pump) #'ignore))
      (james/org-ocr-directory root))
    (should (= 1 (length james/org-ocr--queue)))
    (should (eq (current-buffer)
                (marker-buffer (james/org-ocr-job-marker (car james/org-ocr--queue)))))
    (should (string-match-p "Unsaved backfill note" (buffer-string)))
    (should-not (with-temp-buffer
                  (insert-file-contents note-file)
                  (string-match-p "Unsaved backfill note" (buffer-string))))))

(ert-deftest james/org-ocr-missing-engine-does-not-break-image-insertion ()
  (james-test/with-ocr
    (let ((james/org-ocr-program "/nonexistent/tesseract"))
      (erase-buffer)
      (org-download-insert-link image-file image-file)
      (should (string-match-p "file:slide.png" (buffer-string)))
      (should-not james/org-ocr--process))))

(ert-deftest james/org-ocr-drawer-preserves-list-membership-and-undo ()
  (james-test/with-ocr
    (erase-buffer)
    (insert "* Slides\n- [[file:slide.png]]\n- Next item\n")
    (goto-char (point-min))
    (search-forward "[[")
    (backward-char 2)
    (let ((before (buffer-string)))
      (should (james/org-ocr--apply (james-test/ocr-job) "List slide"))
      (goto-char (point-min))
      (search-forward "List slide")
      (should (org-element-lineage (org-element-context) '(item) t))
      (undo-only 1)
      (should (equal before (buffer-string))))))

(ert-deftest james/org-ocr-queue-runs-one-process-at-a-time ()
  (james-test/with-ocr
    (goto-char (point-max))
    (insert "[[file:slide.png]]\n")
    (james/org-ocr-buffer)
    (should (= 1 (length james/org-ocr--queue)))
    (let ((first james/org-ocr--process)
          (deadline (+ (float-time) 5)))
      (process-send-string first "complete\n")
      (while (and (eq first james/org-ocr--process) (< (float-time) deadline))
        (accept-process-output nil 0.02))
      (should-not (eq first james/org-ocr--process)))
    (should-not james/org-ocr--queue)
    (james-test/ocr-complete)
    (should (= 2 (length (org-element-map (org-element-parse-buffer) 'drawer #'identity))))))

(ert-deftest james/org-ocr-native-download-failure-does-not-start-recognition ()
  (james-test/with-ocr
    (let (completion)
      (cl-letf (((symbol-function 'url-retrieve)
                 (lambda (_url callback &optional arguments &rest _)
                   (setq completion
                         (lambda ()
                           (with-temp-buffer
                             (apply callback '(:error (error http 404)) arguments)))))))
        (org-download--image/url-retrieve "https://example.invalid/x" image-file))
      (goto-char (point-max))
      (org-download-insert-link "https://example.invalid/x" image-file)
      (should-error (funcall completion))
      (should-not james/org-ocr--process)
      (should-not james/org-ocr--queue))))

(ert-deftest james/org-ocr-timeout-cleans-up-and-preserves-note ()
  (james-test/with-ocr
    (let ((james/org-ocr-timeout 0)
          (deadline (+ (float-time) 5)))
      (james/org-ocr-image-at-point)
      (while (and james/org-ocr--process (< (float-time) deadline))
        (accept-process-output nil 0.02))
      (should-not james/org-ocr--process)
      (should-not (buffer-modified-p)))))

(ert-deftest james/org-ocr-deleted-link-cannot-retarget-an-identical-next-link ()
  (james-test/with-ocr
    (erase-buffer)
    (insert "[[file:slide.png]]\n[[file:slide.png]]\n")
    (goto-char (point-min))
    (let ((job (james-test/ocr-job)))
      (delete-region (point) (1+ (line-end-position)))
      (should-not (james/org-ocr--apply job "Deleted slide"))
      (should-not (string-match-p ":OCR:" (buffer-string))))))

;;; james-org-ocr-test.el ends here
